import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import '../models/models.dart';
import '../models/parent_user.dart';
import '../models/teacher_user.dart';
import '../services/multi_user_auth_service.dart';
import '../utils/utils.dart';
import '../widgets/widgets.dart';

class TestRegistrationScreen extends StatefulWidget {
  const TestRegistrationScreen({Key? key}) : super(key: key);

  @override
  State<TestRegistrationScreen> createState() => _TestRegistrationScreenState();
}

class _TestRegistrationScreenState extends State<TestRegistrationScreen> {
  bool _isLoading = false;
  String _result = '';

  Future<void> _testStudentRegistration() async {
    setState(() {
      _isLoading = true;
      _result = 'Testing student registration...';
    });

    try {
      final authService = MultiUserAuthService();

      // Create a dummy image file for testing
      final ImagePicker picker = ImagePicker();
      final XFile? dummyImage = await picker.pickImage(source: ImageSource.gallery);

      if (dummyImage == null) {
        setState(() {
          _result = 'No image selected. Please select an image to test registration.';
          _isLoading = false;
        });
        return;
      }

      final user = await authService.registerStudent(
        fullName: 'Test Student',
        email: 'test.student@example.com',
        phone: '9876543210',
        dateOfBirth: DateTime(2000, 1, 1),
        gender: Gender.male,
        password: 'testpassword123',
        educationCategory: EducationCategory.tenthPass,
        institutionName: 'Test School',
        academicYear: '2023-24',
        parentContact: '9876543211',
        preferredLanguage: Language.english,
        address: '123 Test Street',
        state: 'Test State',
        district: 'Test District',
        city: 'Test City',
        pincode: '123456',
        identityType: 'Aadhaar Card',
        identityNumber: '123456789012',
        identityProofImage: dummyImage,
      );

      setState(() {
        _result = '''
✅ Student Registration Successful!

🗄️ NeonDB PostgreSQL Entry:
- Database: neondb (Your actual database)
- Table: students
- ID: ${user.id} (Auto-generated by NeonDB)
- Created: ${user.createdAt?.toLocal().toString().split('.')[0]}
- Pooled Host: ep-soft-sky-a4h1bku6-pooler.us-east-1.aws.neon.tech
- Unpooled Host: ep-soft-sky-a4h1bku6.us-east-1.aws.neon.tech

👤 User Details:
- Name: ${user.name}
- Email: ${user.email}
- Phone: ${user.phone}
- DOB: ${user.dateOfBirth?.toLocal().toString().split(' ')[0]}
- Gender: ${user.gender?.displayName}

🎓 Education Details:
- Category: ${user.educationCategory?.displayName}
- Institution: ${user.institutionName}
- Academic Year: ${user.academicYear}
- Parent Contact: ${user.parentContact}

📍 Address Information:
- Address: ${user.address}
- City: ${user.city}, ${user.state}
- Pincode: ${user.pincode}

🔐 Security:
- Password: Hashed with SHA-256
- Identity Type: ${user.identityProofType}
- Identity Number: ${user.identityProofNumber}

✅ Data successfully saved to your NeonDB PostgreSQL instance!
🔗 Connection: SSL-secured connection to your cloud database
        ''';
      });
    } catch (e) {
      setState(() {
        _result = '❌ Registration failed: ${e.toString()}';
      });
    } finally {
      setState(() {
        _isLoading = false;
      });
    }
  }

  Future<void> _testParentRegistration() async {
    setState(() {
      _isLoading = true;
      _result = 'Testing parent registration...';
    });

    try {
      final authService = MultiUserAuthService();

      final parentUser = await authService.registerParent(
        fullName: 'Test Parent',
        email: 'test.parent@example.com',
        phone: '9876543212',
        occupation: 'Engineer',
        relationshipType: RelationshipType.father,
        studentRegistrationId: 'STU123456',
        address: '456 Parent Street',
        state: 'Test State',
        district: 'Test District',
        city: 'Test City',
        pincode: '123456',
        preferredLanguage: Language.english,
        password: 'testpassword123',
      );

      setState(() {
        _result = '''
✅ Parent Registration Successful!

Parent Details:
- ID: ${parentUser.id}
- Name: ${parentUser.name}
- Email: ${parentUser.email}
- Phone: ${parentUser.phone}
- Occupation: ${parentUser.occupation}
- Relationship: ${parentUser.relationshipType.displayName}
- Student ID: ${parentUser.studentRegistrationId}
- Address: ${parentUser.city}, ${parentUser.state}
- Verified: ${parentUser.isVerified}

✅ Data saved to backend successfully!
        ''';
      });
    } catch (e) {
      setState(() {
        _result = '❌ Parent registration failed: ${e.toString()}';
      });
    } finally {
      setState(() {
        _isLoading = false;
      });
    }
  }

  Future<void> _testTeacherRegistration() async {
    setState(() {
      _isLoading = true;
      _result = 'Testing teacher registration...';
    });

    try {
      final authService = MultiUserAuthService();

      final teacherUser = await authService.registerTeacher(
        fullName: 'Test Teacher',
        employeeId: 'EMP123456',
        institutionName: 'Test College',
        designation: 'Assistant Professor',
        subjectExpertise: ['Mathematics', 'Physics'],
        email: 'test.teacher@example.com',
        phone: '9876543213',
        yearsOfExperience: 5,
        institutionAddress: '789 College Street',
        state: 'Test State',
        district: 'Test District',
        city: 'Test City',
        pincode: '123456',
        accessLevel: AdminAccessLevel.intermediate,
        preferredLanguage: Language.english,
        password: 'testpassword123',
      );

      setState(() {
        _result = '''
✅ Teacher Registration Successful!

Teacher Details:
- ID: ${teacherUser.id}
- Name: ${teacherUser.name}
- Employee ID: ${teacherUser.employeeId}
- Email: ${teacherUser.email}
- Phone: ${teacherUser.phone}
- Institution: ${teacherUser.institutionName}
- Designation: ${teacherUser.designation}
- Subjects: ${teacherUser.subjectExpertise.join(', ')}
- Experience: ${teacherUser.yearsOfExperience} years
- Access Level: ${teacherUser.accessLevel.displayName}
- Address: ${teacherUser.city}, ${teacherUser.state}
- Verified: ${teacherUser.isVerified}

✅ Data saved to backend successfully!
        ''';
      });
    } catch (e) {
      setState(() {
        _result = '❌ Teacher registration failed: ${e.toString()}';
      });
    } finally {
      setState(() {
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: const Text('Test Backend Registration'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(AppDimensions.paddingL),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text(
              'Your Existing NeonDB Integration Test',
              style: AppTextStyles.headline2,
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: AppDimensions.paddingL),

            Text(
              'Test registration with your existing NeonDB PostgreSQL database. Your database already has 25 tables, 13 education categories, and 52 test sets ready!',
              style: AppTextStyles.bodyText1,
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: AppDimensions.paddingM),

            _buildConnectionInfo(),
            const SizedBox(height: AppDimensions.paddingXL),

            // Test Student Registration
            CustomButton(
              text: 'Test Student Registration',
              onPressed: _testStudentRegistration,
              isLoading: _isLoading,
              isFullWidth: true,
            ),
            const SizedBox(height: AppDimensions.paddingL),

            // Test Parent Registration
            CustomButton(
              text: 'Test Parent Registration',
              onPressed: _testParentRegistration,
              isLoading: _isLoading,
              isFullWidth: true,
            ),
            const SizedBox(height: AppDimensions.paddingL),

            // Test Teacher Registration
            CustomButton(
              text: 'Test Teacher Registration',
              onPressed: _testTeacherRegistration,
              isLoading: _isLoading,
              isFullWidth: true,
            ),
            const SizedBox(height: AppDimensions.paddingXL),

            // Database Statistics
            _buildDatabaseStats(),
            const SizedBox(height: AppDimensions.paddingL),

            // Results
            if (_result.isNotEmpty) ...[
              Container(
                padding: const EdgeInsets.all(AppDimensions.paddingL),
                decoration: BoxDecoration(
                  color: _result.contains('✅') ? AppColors.success.withOpacity(0.1) : AppColors.error.withOpacity(0.1),
                  border: Border.all(
                    color: _result.contains('✅') ? AppColors.success : AppColors.error,
                  ),
                  borderRadius: BorderRadius.circular(AppDimensions.radiusM),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Test Results:',
                      style: AppTextStyles.subtitle1.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: AppDimensions.paddingS),
                    Text(
                      _result,
                      style: AppTextStyles.bodyText2,
                    ),
                  ],
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildDatabaseStats() {
    return Container(
      padding: const EdgeInsets.all(AppDimensions.paddingL),
      decoration: BoxDecoration(
        color: AppColors.primary.withOpacity(0.1),
        border: Border.all(color: AppColors.primary),
        borderRadius: BorderRadius.circular(AppDimensions.radiusM),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            '📊 Database Statistics',
            style: AppTextStyles.subtitle1.copyWith(
              fontWeight: FontWeight.bold,
              color: AppColors.primary,
            ),
          ),
          const SizedBox(height: AppDimensions.paddingM),
          FutureBuilder<Map<String, int>>(
            future: _getDatabaseStats(),
            builder: (context, snapshot) {
              if (snapshot.hasData) {
                final stats = snapshot.data!;
                return Column(
                  children: [
                    _buildStatRow('👥 Total Users', '${stats['total_users']}'),
                    _buildStatRow('🎓 Students', '${stats['total_students']}'),
                    _buildStatRow('👨‍👩‍👧‍👦 Parents', '${stats['total_parents']}'),
                    _buildStatRow('👨‍🏫 Teachers', '${stats['total_teachers']}'),
                  ],
                );
              }
              return const CircularProgressIndicator();
            },
          ),
        ],
      ),
    );
  }

  Widget _buildStatRow(String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: AppDimensions.paddingXS),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: AppTextStyles.bodyText1),
          Text(
            value,
            style: AppTextStyles.subtitle1.copyWith(
              fontWeight: FontWeight.bold,
              color: AppColors.primary,
            ),
          ),
        ],
      ),
    );
  }

  Future<Map<String, int>> _getDatabaseStats() async {
    final authService = MultiUserAuthService();
    return await authService.getDatabaseStatistics();
  }

  Widget _buildConnectionInfo() {
    return Container(
      padding: const EdgeInsets.all(AppDimensions.paddingM),
      decoration: BoxDecoration(
        color: AppColors.info.withOpacity(0.1),
        border: Border.all(color: AppColors.info),
        borderRadius: BorderRadius.circular(AppDimensions.radiusM),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            '🔗 Your Existing NeonDB Database',
            style: AppTextStyles.subtitle1.copyWith(
              fontWeight: FontWeight.bold,
              color: AppColors.info,
            ),
          ),
          const SizedBox(height: AppDimensions.paddingM),
          _buildConnectionRow('🏠 Pooled Host', 'ep-soft-sky-a4h1bku6-pooler.us-east-1.aws.neon.tech'),
          _buildConnectionRow('🏠 Unpooled Host', 'ep-soft-sky-a4h1bku6.us-east-1.aws.neon.tech'),
          _buildConnectionRow('🗄️ Database', 'neondb'),
          _buildConnectionRow('👤 Username', 'neondb_owner'),
          _buildConnectionRow('🔐 SSL Mode', 'require'),
          _buildConnectionRow('📊 Total Tables', '25 (fully configured)'),
          _buildConnectionRow('📚 Education Categories', '13 (ready to use)'),
          _buildConnectionRow('📝 Test Sets', '52 (4 per category)'),
          _buildConnectionRow('🔍 Indexes', '25 custom indexes'),
          _buildConnectionRow('🔗 Foreign Keys', '19 relationships'),
          const SizedBox(height: AppDimensions.paddingS),
          Container(
            padding: const EdgeInsets.all(AppDimensions.paddingS),
            decoration: BoxDecoration(
              color: AppColors.success.withOpacity(0.1),
              borderRadius: BorderRadius.circular(AppDimensions.radiusS),
            ),
            child: Text(
              '🎉 Your database is already production-ready with complete PathfinderAI schema!',
              style: AppTextStyles.bodyText2.copyWith(
                color: AppColors.success,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildConnectionRow(String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: AppDimensions.paddingXS),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 100,
            child: Text(
              label,
              style: AppTextStyles.bodyText2.copyWith(
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
          Expanded(
            child: Text(
              value,
              style: AppTextStyles.bodyText2,
            ),
          ),
        ],
      ),
    );
  }
}
